mutation CreatePublicMovieList($name: String!, $description: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieList_insert(data: {
    name: $name,
    description: $description,
    isPublic: true,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

query GetPublicMovieLists @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  movieLists(where: {isPublic: {eq: true}}) {
    id
    name
    description
  }
}

mutation AddMovieToList($movieListId: UUID!, $movieId: UUID!, $position: Int!) @auth(level: USER) {
  movieListEntry_insert(data: {
    movieListId: $movieListId,
    movieId: $movieId,
    position: $position
  })
}

query GetMyMovieLists @auth(level: USER) {
  movieLists(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    name
    description
  }
}